CREATE TABLE IF NOT EXISTS "notifications" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "userId" INTEGER NOT NULL,
    "sourceId" INTEGER NOT NULL,
    "type" TEXT NOT NULL,
    "seen" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "actioned" INTEGER NOT NULL DEFAULT 0,
    "groupJoinerId" INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (userId) REFERENCES users (id) ON DELETE CASCADE
);